import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://system.netsuite.com/pages/customerlogin.jsp?country=UK');
  //await page.getByRole('link', { name: 'Customer Login', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('ashiyani@sererra.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('QA@Mission9');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('row', { name: '1.0 Product Development' }).getByRole('link').click();
  //await page.getByRole('textbox', { name: '-digit code' }).fill('321348');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('#uif8063').click();
  await page.locator('#angularFrame').contentFrame().locator('a:nth-child(4)').click();
  await page.locator('#angularFrame').contentFrame().getByRole('list').getByText('Quick Entry').click();
  await page.locator('#angularFrame').contentFrame().locator('.new-ng-select.error-dropdown > .ng-select-container > .ng-value-container > .ng-input').first().click();
  await page.locator('#angularFrame').contentFrame().locator('.new-ng-select.error-dropdown > .ng-select-container > .ng-arrow-wrapper').first().click();
  await page.locator('#angularFrame').contentFrame().locator('.new-ng-select.error-dropdown > .ng-select-container > .ng-arrow-wrapper').first().click();
  await page.locator('#angularFrame').contentFrame().getByText(': NCO Solutions').click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Select Group' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Select Group' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByRole('listbox', { name: 'Options list' }).getByPlaceholder('Search').click();
  await page.locator('#angularFrame').contentFrame().getByRole('listbox', { name: 'Options list' }).getByPlaceholder('Search').fill('Test 1');
  await page.locator('#angularFrame').contentFrame().getByText('Group Not Found, Create "Test').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Add', exact: true }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Test Consumable Item').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Select Group' }).locator('div').nth(3).click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Test').click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Walkie Talkie').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByRole('option', { name: 'Dual Sensors Pharmacy/Vaccine' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Select Group' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Test').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).locator('span').first().click();
  await page.locator('#angularFrame').contentFrame().getByText('NG Serialized Invt Item', { exact: true }).click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Select Group' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Test').click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('x 40 x 9').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('div').filter({ hasText: /^Select Group$/ }).nth(1).click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Test').click();
  await page.locator('#angularFrame').contentFrame().locator('div').filter({ hasText: /^Type to add an item$/ }).nth(1).click();
  await page.locator('#angularFrame').contentFrame().getByText('NG Serialized Invt Item for').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('div').filter({ hasText: /^Select Group$/ }).nth(1).click();
  await page.locator('#angularFrame').contentFrame().getByRole('option', { name: 'Test' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().locator('#ace285247113-2 div').filter({ hasText: 'Test Non Rental Service Item' }).click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Select Group' }).locator('div').nth(3).click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Test').click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('x 40 x 9').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Select Group' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Test').click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).locator('div').nth(3).click();
  await page.locator('#angularFrame').contentFrame().getByText('QA Serialized New').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Select Group' }).getByRole('combobox').click();
  await page.locator('#angularFrame').contentFrame().getByLabel('Options list').getByText('Test').click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).locator('div').nth(3).click();
  await page.locator('#angularFrame').contentFrame().getByText('KDP NSI - Marmot Always Summer').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
  await page.locator('#angularFrame').contentFrame().locator('ng-select').filter({ hasText: 'Type to add an item' }).locator('span').first().click();
  await page.locator('#angularFrame').contentFrame().getByText('Ford Everest').click();
  await page.locator('#angularFrame').contentFrame().getByRole('button', { name: 'Quick Add' }).click();
});